name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
    
env: 
  IMG: redis:7.4.1
  OUTPUT: redis741.tar
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: PULL IMAGE 
      run: docker pull $IMG
    - run: mkdir out
    - run: ls
    - run: pwd
    - name: Save Docker image to tar file
      run: docker save $IMG -o out/$OUTPUT
    - run: touch out/out

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
          name: out
          path: out

