name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
    
env: 
  IMG: nginx:alpine
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: PULL IMAGE 
      run: docker pull $IMG
    - name: Save Docker image to tar file
      run: docker save $IMG -o $IMG.tar
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
          name: $IMG.tar
          path: /

